In [5]:
import numpy as np

org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬 - 원본 불변
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후, 반환된 정렬행렬:', sort_array1)
print('np.sort() 호출 후, 반환된 정렬행렬:', org_array)

# ndarray.sort()로 정렬 - 원본 유변
sort_array2 = org_array.sort()
print('sort() 호출 후, 반환된 정렬행렬:', sort_array2)
print('sort() 호출 후, 반환된 정렬행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후, 반환된 정렬행렬: [1 3 5 9]
np.sort() 호출 후, 반환된 정렬행렬: [3 1 9 5]
sort() 호출 후, 반환된 정렬행렬: None
sort() 호출 후, 반환된 정렬행렬: [1 3 5 9]


In [6]:
def add(a,b):
    print('%d와 %d d의 합은 %d입니다.' %(a,b, a+b))

In [7]:
abc = add(3,4)

3와 4 d의 합은 7입니다.


In [9]:
# 내림차순 정렬
desc_array1 = np.sort(org_array)[::-1]
print('내림차순 정렬:', desc_array1)

내림차순 정렬: [9 5 3 1]


In [12]:
# axis에 따른 정렬 - 2차원
array2d = np.array([[8,12], 
                   [7,1]])

# row 방향: 행 기준으로 위아래 비교
sort_array2d_ax0 = np.sort(array2d, axis=0)
print('axis=0 (row):\n', sort_array2d_ax0)

# col 방향: 열 기준으로 양옆 비교
sort_array2d_ax1 = np.sort(array2d, axis=1)
print('axis=1 (col):\n', sort_array2d_ax1)

axis=0 (row):
 [[ 7  1]
 [ 8 12]]
axis=1 (col):
 [[ 8 12]
 [ 1  7]]


* argsort() 함수: 정렬된 행렬의 인덱스 변환

In [14]:
# 
org_array = np.array([3,1,9,5])  # --> 1 3 9 5
                    # 0 1 2 3    # --> 1 0 3 2
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 후, 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 후, 원본 행렬의 인덱스: [1 0 3 2]


###  행렬의 내적 (:: 행렬곱)

In [15]:
# 2 X 3
A = np.array([[1,2,3],
             [4,5,6]])

# 3 X n
B = np.array([[7,8],
             [9,10],
             [11,12]])

np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

###  전치행렬 (Transpose)

In [20]:
A = np.array([[1,2],
             [3,4]])

tra_A = np.transpose(A)

B = np.array([[1,2],
             [3,4],
             [5,6]])

tra_B = np.transpose(B)

tra_A, tra_B

(array([[1, 3],
        [2, 4]]),
 array([[1, 3, 5],
        [2, 4, 6]]))

### Pandas - index

In [21]:
data = {'Name':['Chulmin','Eunkyoung','Jiwoong','Soobeom'],
        'Year':[2011,2016,2015,2015],
        'Gender':['Male','Female','Male','Male'],
        }

In [22]:
import pandas as pd

data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [37]:
# indexing - 1. col(열)은 컬럼명으로
data_df[['Name', 'Year']]

Name  Year
one      Chulmin  2011
two    Eunkyoung  2016
three    Jiwoong  2015
four     Soobeom  2015

In [38]:
# indexing - 2. row(행)은 오직 슬라이싱만!
data_df[0:3]

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male

In [40]:
# 단일값 불러오기

# loc(label::명칭 기반)
data_df.loc['three', 'Name']

# iloc(positional indexing::위치 기반)
data_df.iloc[2, 0]


'Jiwoong'

#### example

In [41]:
data_df

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [47]:
print(data_df.iloc[0:2, 0:2])
print(data_df.iloc[0:2, [0,1]])
print(data_df.iloc[[0,2], [0,1]])
print(data_df.loc['one':'two', 'Name':'Year'])

          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016
          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016
          Name  Year
one    Chulmin  2011
three  Jiwoong  2015
          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016


In [49]:
data_df[data_df['Year']==2015]

Name  Year Gender
three  Jiwoong  2015   Male
four   Soobeom  2015   Male

In [55]:
data_df[data_df['Year']>2014]
data_df.loc[data_df['Year']>2014][:2]


Name  Year  Gender
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male

In [58]:
### 타이타닉 데이터의 index의 특징
titan_df = pd.read_csv('./titanic/train.csv')
titan_df

# index 객체 추출
Indexes = titan_df.index
print(Indexes)

# index 객체를 실제 깞 array로 변환
print('Index 객체 array 값:\n', Indexes.values[:5])

RangeIndex(start=0, stop=891, step=1)
Index 객체 array 값:
 [0 1 2 3 4]


In [61]:
print(type(Indexes.values))
print(Indexes.values.shape)

<class 'numpy.ndarray'>
(891,)


In [66]:
# 한 번에 index 값 변경 X
Indexes[0]=1000  # error

# if index 값을 바꾸고 싶다면, Index.values 를 하고
# 변화한 값을 다시그 pd.DataFrame(index=Index.values) 로 바꿔야 함.

TypeError: Index does not support mutable operations