### Boolean Indexing

In [1]:
import numpy as np 

     ---------------------------------------- 10.4/10.4 MB 8.0 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
array1d = np.arange(start=1, stop=10)
array1d[array1d>5]

array([6, 7, 8, 9])

In [9]:
for i in array1d:
    if i>5:
        print(i, end = ' ')
    else:
        pass

6 7 8 9 

In [13]:
# 두번째 방법
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array1d[boolean_indexes]

array([6, 7, 8, 9])

### 행렬의 정렬 - sort()와 argsort()

In [16]:
org_array = np.array([3,1,9,5])
print('원본행렬:', org_array)

# 1. np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 적용 후 원본행렬:', org_array)
print('np.sort() 적용 후 반환된 정렬행렬:', sort_array1)

# 2. ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 적용 후 원본행렬:', org_array)
print('org_array.sort() 적용 후 반환된 정렬행렬:', sort_array2)

원본행렬: [3 1 9 5]
np.sort() 적용 후 원본행렬: [3 1 9 5]
np.sort() 적용 후 반환된 정렬행렬: [1 3 5 9]
org_array.sort() 적용 후 원본행렬: [1 3 5 9]
org_array.sort() 적용 후 반환된 정렬행렬: None


In [18]:
# 내림차순 정렬[::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print()

array([9, 5, 3, 1])