In [15]:
# scikit-learn 설치
# !pip install scikit-learn
import numpy as np
import pandas as pd
# if Scikit-learn 버전 확인,
import sklearn
print(sklearn.__version__)

1.1.3


In [13]:
# 데이터셋 정의 - iris_data()
from sklearn.datasets import load_iris
iris = load_iris()  # data 형태는 dict.
# 'target'이 범주형 데이터이므로, '분류분석' 해야함.
X_features = iris.data
y_label = iris.target

col_names = ['sep.len', 'sep.wid', 'pet.len', 'pet.wid']
iris_df = pd.DataFrame(data = X_features, columns = col_names)
iris_df['target'] = y_label

iris_df

sep.len  sep.wid  pet.len  pet.wid  target
0        5.1      3.5      1.4      0.2       0
1        4.9      3.0      1.4      0.2       0
2        4.7      3.2      1.3      0.2       0
3        4.6      3.1      1.5      0.2       0
4        5.0      3.6      1.4      0.2       0
..       ...      ...      ...      ...     ...
145      6.7      3.0      5.2      2.3       2
146      6.3      2.5      5.0      1.9       2
147      6.5      3.0      5.2      2.0       2
148      6.2      3.4      5.4      2.3       2
149      5.9      3.0      5.1      1.8       2

[150 rows x 5 columns]

학습(훈련)용 데이터 & 테스트용 데이터 분리해보자.

훈련용 데이터와 테스트용 데이터는 반드시 분리할 것.

In [14]:
from sklearn.model_selection import train_test_split

In [18]:
?train_test_split

In [34]:
# train_test_split (EX)
array1 = np.arange(1, 11)
train_test_split(array1, test_size=0.2)  # 'array1' 데이터 중 20%를 test로 하겠다. --> enter 할 때마다 값이 바뀜. 
array_train, array_test = train_test_split(array1, test_size=0.2, random_state=11)  # 'array1' 데이터 중 20%를 test로 하겠다. --> enter 할 때마다 값이 동일하게. 

In [35]:
# train_test_split (EX)
array_test

array([8, 9])

In [36]:
# train_test_split (EX)
array_train

array([ 3,  7,  5,  6,  2,  4,  1, 10])

In [ ]:
# 두 줄로 코드를 쓴다면, 아래와 같음.
X_train, X_test = train_test_split(X_features, test_size=0.2, random_state=11)
y_train, y_test = train_test_split(y_label, test_size=0.2, random_state=11

In [37]:
# 실무에서는 아래와 같은 코드 사용
X_train, X_test, y_train, y_test = train_test_split(X_features, y_label, test_size=0.2, random_state=11)

In [43]:
# 각 데이터의 shape
X_train.shape, y_train.shape  # 120개로 동일

((120, 4), (120,))

In [42]:
X_test.shape, y_test.shape  # 30개로 동일

((30, 4), (30,))

In [44]:
# 분류분석에 쓰일 알고리즘 loading - 의사결정나무(Descision Tree Classifier)
# Black-Box
from sklearn.tree import DecisionTreeClassifier  # cf. 'DecisionTreeRegressor' --> 회귀분석에 쓰이는 알고리즘

In [45]:
# ?DecisionTreeClassifier

In [46]:
# 알고리즘 객체화
dt_clf = DecisionTreeClassifier(random_state=11)

In [47]:
# 학습 수행 (Black-Box에 train data 넣기) - fit() estimator 활용하여 '적합'시키다.
dt_clf.fit(X_train, y_train)  # 의사결정나무 Black-Box에 train data로 수행 --> 수행된 데이터는 사라짐.
# 전체 데이터 중 (150개) 120개 학습에 사용

DecisionTreeClassifier(random_state=11)

In [49]:
# 학습된 dt_clf 모델을 토대로, 분류예측 수행 - 'X_test' 값만 삽입
y_pred = dt_clf.predict(X_test)  # 30개만 현제 데이터에 예측 재료로 사용 --> 예측(prediction)된 값 도출

In [50]:
# 예측값
y_pred 

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [51]:
# 실제값
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [53]:
# 예측값과 실제값을 비교해보니 2개가 틀림. --> 예측 정확도 93% --> 좀더 정확하게 도출하려면?
# 평가지표(metrics) 호출
from sklearn.metrics import accuracy_score as acc_sc  # naming이 기니까 acc_sc로 축약어 사용

In [54]:
acc_sc(y_test, y_pred)

0.9333333333333333